### ISSUE TITLE
Personal distress about cross relation sharing

### ISSUE THREAD

**Issue by nwt-musicApplication** [tmliang/CGRE#7]
Dear Author, I have found in my personal crude research that sometimes the mechanism of information propagation between relations improves the performance of long-tail relations while causing a slight decrease in denoising metrics (P@N and AUC values), have you ever encountered a similar situation?

**Comment by tmliang** [comment]
There are two frequently-used ways to improve long-tail classification: 

[1]. re-distribution (such as re-sampling, re-weighting); 

[2]. incorporating external knowledge for long-tail classes.

Methods [1] are actually improving long-tail performance at the expense of head performance, so they would definitely decrease the overall performance (after all, head classes occupy most instances). 

Our method belongs to [2], which should be able to improve both the overall and long-tail performance, because the improvment are originally from the external knowlege, instead of doing a balance between head and long-tail. 

So, I guess your current method belongs to [1]?
